name: github CI discord

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: echo "Server already started"
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 # waits for 1 minute for your server to start
